on:
  push
name: make test
jobs:
  test:
    name: make test
    runs-on: ubuntu-latest
    steps:
      - uses: actions
        with:
          fetch-depth: '2'
      - name: dockertest
        run: dockertest
        shell: bash
