version: "3"
services:
  tor:
    container_name: tor
    image: dockurr/tor:latest
    ports:
      - 8080:8080
      - 8080:8081
    restart: always
    volumes:
      - /path/to/config:/etc/tor
      - /path/to/data:/var/lib/tor
    stop_grace_period: 1m